--1
SELECT DISTINCT CITY FROM STATION WHERE MOD(ID,2) = 0;
--2 Euclidean Distance
SELECT ROUND(SQRT(POWER(MIN(LONG_W)-MAX(LONG_W),2)+POWER(MIN(LAT_N)-MAX(LAT_N),2)),4)
FROM STATION;
--3 Friend salary > My salary
SELECT S.Name
FROM Students AS S
INNER JOIN Friends AS F ON S.ID = F.ID
INNER JOIN Packages AS MY ON S.ID = MY.ID
INNER JOIN Packages AS FP ON F.Friend_ID = FP.ID
WHERE FP.Salary > MY.Salary
ORDER BY FP.Salary ASC
--4 Binary Tree
SELECT MY.N, CASE 
        WHEN COUNT(MY.P) = 0 THEN 'Root'
        WHEN COUNT(LEAF.N) = 0 THEN 'Leaf'
        ELSE 'Inner'
    END AS 'Type'
FROM BST AS MY LEFT JOIN BST AS LEAF ON MY.N = LEAF.P
GROUP BY MY.N, MY.P
ORDER BY MY.N ASC;